puts "In your travels you finally come across the tree of future-telling."
puts "You cast the ritual of awakening."
puts "You hear a heavy sigh and old grooves in the tree trunk open to reveal an eye. It gazes at you. Wearily, a voice asks..."
puts "---------------------------------------------"
print "How old are you now? -> "
age = gets.chomp.to_i
puts "---------------------------------------------"
puts "The tree is silent for a while, and then says..."
puts "---------------------------------------------"
puts "In 10 years you will be #{age + 10}."
puts "In 20 years you will be #{age + 20}."
puts "In 30 years you will be #{age + 30}."
puts "In 40 years you will be #{age + 40}."
puts "---------------------------------------------"
puts "A rumbling in the forest, the eye closes, and then all is silent again. The tree is asleep."
puts "You kick the dirt at your feet. This was a waste of time."